Document: gfxreconstruct
Title: Debian gfxreconstruct Manual
Author: <insert document author here>
Abstract: This manual describes what gfxreconstruct is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gfxreconstruct/gfxreconstruct.sgml.gz

Format: postscript
Files: /usr/share/doc/gfxreconstruct/gfxreconstruct.ps.gz

Format: text
Files: /usr/share/doc/gfxreconstruct/gfxreconstruct.text.gz

Format: HTML
Index: /usr/share/doc/gfxreconstruct/html/index.html
Files: /usr/share/doc/gfxreconstruct/html/*.html
